-- Add new columns to properties table
ALTER TABLE public.properties
  ADD COLUMN IF NOT EXISTS category text,
  ADD COLUMN IF NOT EXISTS property_type text,
  ADD COLUMN IF NOT EXISTS county text,
  ADD COLUMN IF NOT EXISTS brown_water text,
  ADD COLUMN IF NOT EXISTS has_pool boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS school_score numeric,
  ADD COLUMN IF NOT EXISTS hoa_id integer,
  ADD COLUMN IF NOT EXISTS subdivision text,
  ADD COLUMN IF NOT EXISTS legal_description text,
  ADD COLUMN IF NOT EXISTS renovation_date date,
  ADD COLUMN IF NOT EXISTS source text,
  ADD COLUMN IF NOT EXISTS source_name text,
  ADD COLUMN IF NOT EXISTS date_purchased date,
  ADD COLUMN IF NOT EXISTS date_sold date,
  ADD COLUMN IF NOT EXISTS asset_id_counter integer,
  ADD COLUMN IF NOT EXISTS asset_id text,
  ADD COLUMN IF NOT EXISTS markets_id integer,
  ADD COLUMN IF NOT EXISTS funds_id integer,
  ADD COLUMN IF NOT EXISTS portfolios_id integer,
  ADD COLUMN IF NOT EXISTS deals_id uuid[],
  ADD COLUMN IF NOT EXISTS purchase_price numeric,
  ADD COLUMN IF NOT EXISTS uw_arv numeric,
  ADD COLUMN IF NOT EXISTS uw_rent numeric,
  ADD COLUMN IF NOT EXISTS uw_capex numeric,
  ADD COLUMN IF NOT EXISTS cost_basis numeric;